### ISSUE TITLE
Failed to download dataset 404-file not found

### ISSUE THREAD

**Issue by ambroggi** [rdpahalavan/nids-datasets#1]
The download function was not able to download the dataset. Not sure how to post something for issues so I hope this is an ok format.
Or am I loading it incorrectly.
<img width="900" alt="Screenshot 2023-07-31 at 8 32 39 PM" src="https://github.com/rdpahalavan/nids-datasets/assets/97543940/2d19a3be-b987-4914-8950-1fc36c5eadc8">

**Comment by rdpahalavan** [comment]
Hello @ambroggi, can you provide the complete code? That will help me to debug the error (Dataset class initialization including what dataset, subset and files are used before using data.download()).

**Comment by ambroggi** [comment]
It was (I have a different import named Dataset so I had to change the name.):
```
from nids_datasets import Dataset as DTAset
'CIC-IDS2017''UNSW-NB15'
data=DTAset(dataset='CIC-IDS2017', subset='Payload-Bytes', files='all')
data.download()
data.read()
```

**Comment by rdpahalavan** [comment]
Hello, the problem is you are using a string to represent the subset (subset='Payload-Bytes'). Please pass the values (subset and file) as a list (subset=['Payload-Bytes']). I updated the code to handle both strings and lists. Please update the package using "**pip install --upgrade nids-datasets**" to use the new version.

**Comment by ambroggi** [comment]
Ah, ok.
